### ISSUE TITLE
Paramiko installation check fails without setuptools

### ISSUE THREAD

**Issue by robyurkowski** [guilro/trellis-backup-role#1]
I'm not sure if this is a standard thing or just a 'me and my personal dev environment setup' thing, but when I try to provision a remote server, installation fails because the setuptools python module can't be found and therefore paramiko can't be installed.

What I did to resolve it was simply SSH in to the box, and run a `sudo pip install setuptools`, but if others experience this, there's obviously a superior ansible-based solution to this. Just wanted to document this (other keywords that I hunted for: trellis setuptools paramiko) in case someone else bumps into it.

**Comment by apmarshall** [comment]
Seconding this issue. If you know of an ansible-based solution, would love to see it.
