### ISSUE TITLE
Errors on restore

### ISSUE THREAD

**Issue by fabiohsouza** [guilro/trellis-backup-role#10]
Hello!

I'm setting trellis-backup-role on a test site using Google Cloud Storage.
The backup is ok (uploads/database), but when i try restore i get this errors:

sudo duply example.com_uploads restore

Start duply v1.9.1, time is 2017-09-25 11:31:53.
Using profile '/etc/duply/example.com_uploads'.
Using installed duplicity version 0.7.06, python 2.7.12, gpg 1.4.20 (Home: ~/.gnupg), awk 'GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)', bash '4.3.48(1)-release (x86_64-pc-linux-gnu)'.
Checking TEMP_DIR '/tmp' is a folder (OK)
Checking TEMP_DIR '/tmp' is writable (OK)
TODO: reimplent tmp space check
Test - En/Decryption skipped. (GPG disabled)

--- Start running command RESTORE at 11:31:53.333 ---
Restore destination directory /srv/www/example.com/shared/uploads already exists.
Will not overwrite.
11:31:53.586 Task 'RESTORE' failed with exit code '11'.
--- Finished state FAILED 'code 11' at 11:31:53.586 - Runtime 00:00:00.253 ---

sudo duply example.com_database restore

Start duply v1.9.1, time is 2017-09-25 11:34:32.
Using profile '/etc/duply/example.com_database'.
Using installed duplicity version 0.7.06, python 2.7.12, gpg 1.4.20 (Home: ~/.gnupg), awk 'GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)', bash '4.3.48(1)-release (x86_64-pc-linux-gnu)'.
Checking TEMP_DIR '/tmp' is a folder (OK)
Checking TEMP_DIR '/tmp' is writable (OK)
TODO: reimplent tmp space check
Test - En/Decryption skipped. (GPG disabled)

--- Start running command RESTORE at 11:34:32.604 ---
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Sat Sep 23 10:57:13 2017
Running '/etc/duply/example.com_database/restore' - OK
Output: ERROR 1142 (42000) at line 22: DROP command denied to user 'backup'@'localhost' for table 'wp_commentmeta'
--- Finished state OK at 11:34:35.868 - Runtime 00:00:03.263 ---

**Comment by jillro** [comment]
My bad, seems that creating a read-only user for the backup role in https://github.com/guilro/trellis-backup-role/commit/a8cae4098b07d2c1a138e392c7cf82215c7e5b9d broke the restore command.

**Comment by jillro** [comment]
This is fixed in 2.0.2 !
