### ISSUE TITLE
Trouble using b2 backends without upgrading duplicity

### ISSUE THREAD

**Issue by apmarshall** [guilro/trellis-backup-role#14]
I ran into an issue where backups to b2/backblaze were failing with a 404 error in the BKP step. After doing some research, discovered that this is a [known issue](https://bugs.launchpad.net/duplicity/+bug/1523498) that was fixed in duplicity 0.7.07. Unfortunately, the default in Ubuntu Trusty is 0.7.06. To upgrade, we need to add a new apt repo and then upgrade the package. As this is specific to the OS used in Trellis, I thought it better to include those steps in this plugin rather than in [lafranceinsoumise/ansible-backup](https://github.com/lafranceinsoumise/ansible-backup). Pull request coming momentarily with a suggested fix.

**Comment by jillro** [comment]
This is fixed in https://github.com/lafranceinsoumise/ansible-backup.
