### ISSUE TITLE
Database restore fails

### ISSUE THREAD

**Issue by thomasazar** [guilro/trellis-backup-role#17]
On a fresh Trellis install, the restore command fails with the following message:
`Output: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)`

I have configured `vault_mysql_backup_password` as per the README, but it appears to have no effect. If I modify the restore command in `/etc/duply/website.com_database/restore` to prompt for a password (`mysql -p`), the restore works once I enter the root password.

**Comment by jillro** [comment]
Hello. `vault_mysql_backup_password` is not used anymore as Trellis use `auth_socket` plugin to connect to the database. I just removed it from the README.

If mysql `auth_socket` plugin is activated (as it is on a default Ubuntu install), executing the restore command as root should be enough to access the database. Did you use `sudo` for the restore command ?

`sudo duply website_name_database restore`

**Comment by thomasazar** [comment]
Interesting. It turns out that the `auth_socket` plugin was not installed on my server. I'm not sure if that's due to Trellis or DigitalOcean (where the server is hosted), but installing the plugin fixes the problem. Thanks for setting me straight.
