### ISSUE TITLE
could a more simplier docs be added?

### ISSUE THREAD

**Issue by senadir** [guilro/trellis-backup-role#19]
i know most of those things my sounds very obvious and easy to you, but I'm totally baffled by the docs
everythings start great and easy, once you get to the [vault section](https://github.com/guilro/trellis-backup-role#vaultyml) nothing is obvious
```
    backup_target_user: user
    backup_target_pass: password
``` 

i suppose I should use those values in target value in wordpress sites right?
```
sudo duply website_name_database restore
sudo duply website_name_uploads restore
```
where should I run those commands? vagrant, local pc, server?
should I provision my local vagrant, should I provision the servers?
what value should I use for `website_name_database` and `website_name_uploads`, should I install duply as well?

**Comment by jillro** [comment]
I updated the documentation to be more detailed. But because this project is based on duply, I think you should first get some insights about what is duply and how it works :) You can find some on https://duply.net.
