### ISSUE TITLE
backblaze require B2 Python APIs

### ISSUE THREAD

**Issue by senadir** [guilro/trellis-backup-role#20]
how should I set this up so it is installed on provision?

**Comment by jillro** [comment]
Hello ! I will add an option in the following days to ansible-backup to automatically install optional dependencies specific to some blackends. In the meantime time, you can add it manually as a pre_tasks in your playbook.

**Comment by strarsis** [comment]
@guilro: This would be a great feature for Backblaze B2 users, is this still planned for the near future?

**Comment by amankapoor** [comment]
> Hello ! I will add an option in the following days to ansible-backup to automatically install optional dependencies specific to some blackends. In the meantime time, you can add it manually as a pre_tasks in your playbook.

Hi, I am new to ansible and all these environments. Could you please share how to get it working?

I have been trying without success from long.

I added the following
```

- name: pip
  src: geerlingguy.pip
  version: 1.3.0
```
in ```requirements.yml``` under trellis folder.

Then how do I make it work to install b2? Where should I add that code.

Thanks.

**Comment by amankapoor** [comment]
Solved it, here's how I did it if anyone's stuck. https://github.com/guilro/trellis-backup-role/issues/7#issuecomment-473462260

**Comment by jillro** [comment]
Hello ! Since a few versions https://github.com/lafranceinsoumise/ansible-backup/, which does the biggest part of the job of this role, automatically install the dependencies depending on your target scheme. You should update your galaxy roles in order to get this feature.

**Comment by grahamharper** [comment]
> automatically install the dependencies depending on your target scheme

@jillro how do you use the feature for b2?
