### ISSUE TITLE
Maintenance of trellis-backup-role

### ISSUE THREAD

**Issue by smaboshe** [guilro/trellis-backup-role#25]
@jillro not sure what you are looking for an a maintainer but my team and I would be happy to pick this project up from you. Hope you don't mind helping us through the transition.

Let me know what you need.

**Comment by jillro** [comment]
Sorry, I am in vacation right now. As soon as I'm back we can see this together.

**Comment by smaboshe** [comment]
No problem. I'll wait until you are back. Thank you.

**Comment by jillro** [comment]
Hey ! Here's what I propose : I transfer you the ownership of the repository. Somehow the Galaxy import messed up with my Github username renaming, so I let you create a new Galaxy package, and I deprecate mine. This way, there is also no transfer of trust occuring without users consent. Is it ok for you ?

**Comment by jasperf** [comment]
Any news on the new location for this package?

**Comment by Xilonz** [comment]
Since @smaboshe didn't respond, I'm also willing to take over the repo. I've been using this successfully for over a year now and I'd like it to stay.

**Comment by smaboshe** [comment]
Sorry, everyone, lots going on. Thanks, @Xilonz. Happy for you to take over.

**Comment by jillro** [comment]
Hello ! As everyone seems ok, I'll transfer this repo to @Xilonz.

**Comment by Xilonz** [comment]
@jillro Thank you for making this role.

I'll leave this issue open until I (or someone else) has done the following:
- [x] Update readme
- [x] Publish the package to ansible-galaxy
- [x] Update roots documentation
