### ISSUE TITLE
FTP backup issue - BackendException: Error running 'lftp -c "

### ISSUE THREAD

**Issue by tomektomczuk** [guilro/trellis-backup-role#39]
so I'm trying to backup to FTP. 

I added user and password variables to all/vault.yml When I had them in production vault I get an error that these variables were not set.

```
 backup_target_user: user
 backup_target_pass: password
```

my target is 

`target: ftp://{{ backup_target_user }}[:{{ backup_target_pass }}]@xyz.ftp.dhosting.pl[:21]`

When I get to the server logs at var/log/duply/ is see the following error

```
--- Start running command BKP at 19:45:03.879 ---
LFTP version is 4.8.4
Reading globbing filelist /etc/duply/marcinkujanek.pl_uploads/exclude
Attempt 1 failed. BackendException: Error running 'lftp -c "source /tmp/duplicity-etq94hg0-tempdir/mkstemp-umg8ffmk-1; ( cd uploads/ && ls ) || ( mkdir -p uploads/ && cd uploads/ && ls )"': returned 1, with output:

open: Not connected
cd: Not connected
mkdir: Not connected


Attempt 2 failed. BackendException: Error running 'lftp -c "source /tmp/duplicity-etq94hg0-tempdir/mkstemp-umg8ffmk-1; ( cd uploads/ && ls ) || ( mkdir -p uploads/ && cd uploads/ && ls )"': returned 1, with output:

open: Not connected
cd: Not connected
mkdir: Not connected


Attempt 3 failed. BackendException: Error running 'lftp -c "source /tmp/duplicity-etq94hg0-tempdir/mkstemp-umg8ffmk-1; ( cd uploads/ && ls ) || ( mkdir -p uploads/ && cd uploads/ && ls )"': returned 1, with output:

open: Not connected
cd: Not connected
mkdir: Not connected


Attempt 4 failed. BackendException: Error running 'lftp -c "source /tmp/duplicity-etq94hg0-tempdir/mkstemp-umg8ffmk-1; ( cd uploads/ && ls ) || ( mkdir -p uploads/ && cd uploads/ && ls )"': returned 1, with output:

open: Not connected
cd: Not connected
mkdir: Not connected


Giving up after 5 attempts. BackendException: Error running 'lftp -c "source /tmp/duplicity-etq94hg0-tempdir/mkstemp-umg8ffmk-1; ( cd uploads/ && ls ) || ( mkdir -p uploads/ && cd uploads/ && ls )"': returned 1, with output:

open: Not connected
cd: Not connected
mkdir: Not connected


19:47:05.072 Task 'BKP' failed with exit code '50'.
--- Finished state FAILED 'code 50' at 19:47:05.072 - Runtime 00:02:01.193 ---
```

It's looks like we have to update lftp
[Solution 1](https://answers.launchpad.net/duplicity/+question/694064)

**Comment by rutger1140** [comment]
Could you try to update lftp on your server and try again?

This seems unrelated to both trellis-backup and [ansible-backup](https://github.com/lafranceinsoumise/ansible-backup) roles.

**Comment by tomektomczuk** [comment]
Ok so I find workaround. 
1) I changed to sftp 
2) set target to  pexpect+sftp://{{ backup_target_user }}:{{ backup_target_pass }}@xyz.ssh.dhosting.pl:22
3) log in to the server as a root and change PasswordAuthentication to yes at /etc/ssh/ssh_config

@swalkinshaw is there a better way to do that as every provision changes PasswordAuthentication to no?

**Comment by rutger1140** [comment]
> Ok so I find workaround.
> 
> 1. I changed to sftp
> 2. set target to  pexpect+sftp://{{ backup_target_user }}:{{ backup_target_pass }}@xyz.ssh.dhosting.pl:22
> 3. log in to the server as a root and change PasswordAuthentication to yes at /etc/ssh/ssh_config
> 
> @swalkinshaw is there a better way to do that?

`PasswordAuthentication` should be set to no. This is a [default setting in Trellis](https://github.com/roots/trellis/blob/master/group_vars/all/security.yml#L17) and improves security a lot. 

You’re better of using a separate SSH keypair for backups. That is what we use.

**Comment by tomektomczuk** [comment]
> > Ok so I find workaround.
> > 
> > 1. I changed to sftp
> > 2. set target to  pexpect+sftp://{{ backup_target_user }}:{{ backup_target_pass }}@xyz.ssh.dhosting.pl:22
> > 3. log in to the server as a root and change PasswordAuthentication to yes at /etc/ssh/ssh_config
> > 
> > @swalkinshaw is there a better way to do that?
> 
> `PasswordAuthentication` should be set to no. This is a [default setting in Trellis](https://github.com/roots/trellis/blob/master/group_vars/all/security.yml#L17) and improves security a lot.
> 
> You’re better of using a separate SSH keypair for backups. That is what we use.

So creating SSH on FTP and then adding this key to the Trellis server?

**Comment by tomektomczuk** [comment]
Ok, so I found out that my backup server is reseting the whole system to default setting every day. This means that any new SSH key will be vanished :(

**Comment by rutger1140** [comment]
Guess you have to use the options provided than. 

This is outside the scope of this project. Good luck with your setup!
