### ISSUE TITLE
'vault_mysql_backup_password' is undefined

### ISSUE THREAD

**Issue by smaboshe** [guilro/trellis-backup-role#8]
Hello!

Deployments have broken from me in the last few days. Is this related to the commits that add `mysql_backup_user` (Commit https://github.com/guilro/trellis-backup-role/commit/a8cae4098b07d2c1a138e392c7cf82215c7e5b9d)?

The error I'm getting is ...

```
the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'vault_mysql_backup_password' is undefined

The error appears to have been in '/<path to site>/trellis/vendor/roles/trellis-backup/tasks/main.yml': line 16, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Create backup mysql user
  ^ here

fatal: [default]: FAILED! => {"failed": true}
```
This stops the Ansible tasks to build the development machine from completing:

```
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by jillro** [comment]
Recent development in Trellis have created the necessity to have a mysql user to create the backups. You need to provide the user with a random secured password in your `vault.yml`, as stated in the README.

**Comment by smaboshe** [comment]
Thank you, @guilro. I have added `vault_mysql_backup_password` as described in the `README` (https://github.com/guilro/trellis-backup-role#vaultyml) and it works. Feel free to mark the issue closed.
